version: '3.8'

services: 
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-container
    ports:
      - "8080:8080"
    networks:
      - jenkins-network
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-ssh-container
    networks:
      - jenkins-network
    ports:
      - "2222:22"  
      - "8086:8084"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkins_home:
